---
title: "R&PF Regressions"
output: html_document
date: "2025-07-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(tidyverse)
library(readxl)
library(fixest)
library(purrr)
library(broom)
library(Hmisc)
library(dplyr)
library(ggplot2)
library(GGally)
library(corrplot)
library(urca)
library(apaTables)
library(rlang)
```

```{r}
dat <- read_xlsx("Tangled_Up_In_Blue_Data.xlsx")
```

```{r}
individual_model <- function(dv, dat, term, iv){
  formula <- paste0(dv, " ~ Unemployment_Rate + NH_White_Pct + Age_15_24_Pct + 
                            Educ_Less_HS_Pct + Exp_Per_Capita ", term, "|
                            year + ori|", iv , "~ copseligible_hiring_lag + award_nonhiring_lag + 
                            apply_hiring_lag + apply_nonhiring_lag")

model_object <- feols(as.formula(formula), data = dat, cluster ~ ori, weights = ~w1980factor)
  print(summary(model_object))
}

term_models <- function(term, dv, dat, iv){
  map(dv, ~individual_model(dv = .x, term = term, dat = dat, iv = iv))
}

all_models <- function(dv, terms, dat, iv){
  map(terms, ~term_models(term = .x, dv = dv, dat = dat, iv = iv))
}
```

```{r}
levels_treatment_terms <- c(" ", "+ S_pop", "+ S_black_pct", "+ S_pop + S_black_pct")

fd_treatment_terms <- c(" ", "+ S_d_pop", "+ S_d_black_pct", "+ S_d_pop + S_d_black_pct")

pc_treatment_terms <- c(" ", "+ S_pc_pop", "+ S_pc_black_pct", "+ S_pc_pop + S_pc_black_pct")
```

## Murder 

### Levels 

```{r}
murder_levels_results <- all_models("murder_tot_total", levels_treatment_terms, dat, iv = "S_lag")
```

### First Difference 

```{r}
murder_fd_resutls <- all_models("murder_total_d", fd_treatment_terms, dat, iv = "S_d")
```

## Clearance 

### Levels 

```{r}
clearance_levels_results <- all_models("clearance", levels_treatment_terms, dat, iv = "S_lag")
```

### First Difference 

```{r}
clearance_fd_results <- all_models("clearance_total_d", fd_treatment_terms, dat, iv = "S_d")
```

## Index Arrests

### Levels 

```{r}
iarrest_levels_results <- all_models("iarrest_tot_total", levels_treatment_terms, dat, iv = "S_lag")
```

### First Difference 

```{r}
iarrest_fd_results <- all_models("iarrest_total_d", fd_treatment_terms, dat, iv = "S_d")
```

## Non-Index Arrests 

### Levels 

```{r}
niarrest_levels_results <- all_models("niarrest_tot_total", levels_treatment_terms, dat, iv = "S_lag")
```

### First Difference 

```{r}
niarrest_fd_results <- all_models("niarrest_total_d", fd_treatment_terms, dat, iv = "S_d")
```



